name: Build, Package, and Deploy Nanoforge

on:
  push:
    branches:
      - ruigbriuabguibarpgib # put here for now to avoid it triggering but will work on this in the future
  pull_request:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: run tests
      run: cargo test
